sudo: required
services: 
  - docker

before_install:
  - docker build -t vigneshkarnika/dockertestapp -f Dockerfile.dev .

script:
  - docker run vigneshkarnika/dockertestapp npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "reactdock"
  env: "Reactdock-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-568194335858"
  bucket_path: "reactdock"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY